name: exercism_companion
description: >
  A simple companion to help Dart mentors. 
  This program downloads the code from a Dart exercise on Exercism, enabled all the tests and run them.
homepage: https://github.com/Corentin-Leffy/Exercism-Companion
repository: https://github.com/Corentin-Leffy/Exercism-Companion
issue_tracker: https://github.com/Corentin-Leffy/Exercism-Companion/issues
version: 1.0.2
executables:
  exercism-companion: exercism_companion

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.5.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
